document.addEventListener("DOMContentLoaded", () => {
    const container = document.getElementById("cup-list");
    const searchInput = document.getElementById("search-input");
    const statsContainer = document.getElementById("stats-container");

    let allCups = []; // Store data globally

    // 1. Fetch the JSON data generated by Python
    fetch('bonk_cup_data.json')
        .then(res => {
            if (!res.ok) throw new Error("JSON file not found");
            return res.json();
        })
        .then(data => {
            allCups = data;
            renderStats(allCups);
            renderList(allCups);
        })
        .catch(err => {
            console.error(err);
            container.innerHTML = `
                <div class="loading">
                    <p style="color: #ff4444;">Error loading data.</p>
                    <p style="font-size:0.8rem; color:#ccc;">Make sure 'bonk_cup_data.json' exists.</p>
                </div>`;
        });

    // 2. Render Stats
    function renderStats(data) {
        const totalCups = data.length;
        const uniqueWinners = new Set(
            data.map(c => c.winner).filter(w => w && w !== "Unknown" && w.trim() !== "")
        );

        statsContainer.innerHTML = `
            <div class="stat-card">
                <div class="stat-number">${totalCups}</div>
                <div class="stat-label">Total Cups</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">${uniqueWinners.size}</div>
                <div class="stat-label">Unique Winners</div>
            </div>
        `;
    }

    // 3. Render the Accordion List
    function renderList(cups) {
        container.innerHTML = "";

        if (cups.length === 0) {
            container.innerHTML = "<p style='text-align:center; padding:20px; color:#666;'>No results found.</p>";
            return;
        }

        cups.forEach(cup => {
            const tab = document.createElement("div");
            tab.classList.add("accordion-tab");

            // Date Logic
            let dateStr = "Unknown Date";
            if (cup.display_date) {
                dateStr = cup.display_date; 
            } else if (cup.publish_date) {
                dateStr = new Date(cup.publish_date * 1000).toLocaleDateString();
            }

            // --- USE THE FORMATTER HERE FOR CAMPAIGN TITLE ---
            // (If campaigns also use colors, we fix them here too)
            const formattedCampaignName = formatTmName(cup.campaign_name);

            // 1. Header HTML
            let html = `
                <div class="accordion-header">
                    <div class="cup-info">
                        <span class="edition-badge">#${cup.edition}</span>
                        <div>
                            <div class="cup-title">${formattedCampaignName}</div>
                            <div class="cup-date">${dateStr}</div>
                        </div>
                    </div>
                    <div class="winner-badge">
                        <i class="fas fa-trophy"></i> ${cup.winner || "Unknown"}
                    </div>
                </div>
                
                <div class="accordion-content">
                    <table>
                        <thead>
                            <tr>
                                <th width="50">#</th>
                                <th>Map Name</th>
                                <th>Author</th>
                                <th>Author Time</th>
                            </tr>
                        </thead>
                        <tbody>
            `;

            // 2. Maps Loop
            if (cup.maps && cup.maps.length > 0) {
                cup.maps.forEach((map, index) => {
                    const timeSec = (map.time_author / 1000).toFixed(3);
                    
                    // --- USE THE FORMATTER HERE FOR MAP NAMES ---
                    const formattedMapName = formatTmName(map.name);

                    html += `
                        <tr>
                            <td>${index + 1}</td>
                            <td style="font-weight:500;">
                                <a href="https://trackmania.io/#/leaderboard/${map.uid}" target="_blank" style="color:#fff; text-decoration:underline;">
                                    ${formattedMapName}
                                </a>
                            </td>
                            <td>${map.author}</td>
                            <td>${timeSec}s</td>
                        </tr>
                    `;
                });
            } else {
                html += `<tr><td colspan="4" style="text-align:center; padding:15px;">No maps loaded for this cup.</td></tr>`;
            }

            // 3. Close HTML
            html += `
                        </tbody>
                    </table>
                    <a href="${cup.tm_io_url}" target="_blank" class="tm-btn">
                        View on Trackmania.io <i class="fas fa-external-link-alt" style="margin-left:5px;"></i>
                    </a>
                </div>
            `;

            tab.innerHTML = html;
            container.appendChild(tab);

            const header = tab.querySelector(".accordion-header");
            header.addEventListener("click", () => {
                tab.classList.toggle("active");
            });
        });
    }

    // 4. Search Filter Logic
    searchInput.addEventListener("input", (e) => {
        const query = e.target.value.toLowerCase().trim();

        if (!query) {
            renderList(allCups);
            return;
        }

        const filtered = allCups.filter(cup => {
            const inName = cup.campaign_name.toLowerCase().includes(query);
            const inWinner = (cup.winner || "").toLowerCase().includes(query);
            const inEdition = String(cup.edition).includes(query);
            const inDate = (cup.display_date || "").includes(query);

            let inMaps = false;
            if (cup.maps) {
                inMaps = cup.maps.some(map => 
                    map.name.toLowerCase().includes(query) || 
                    map.author.toLowerCase().includes(query)
                );
            }

            return inName || inWinner || inEdition || inDate || inMaps;
        });

        renderList(filtered);
    });
});

// --- HELPER FUNCTION: Format Trackmania Colors ---
function formatTmName(raw) {
    if (!raw) return "";

    // Split by '$' to isolate codes
    // Example: "$00Fwinter $888goal" -> ["", "00Fwinter ", "888goal"]
    const parts = raw.split('$');
    
    // The first part is always plain text (before the first $)
    let html = parts[0]; 
    
    for (let i = 1; i < parts.length; i++) {
        let part = parts[i];
        
        // Check if the segment starts with a 3-digit hex code (Color)
        // Regex: ^[0-9a-fA-F]{3} checks for 0-9 or A-F exactly 3 times at start
        if (/^[0-9a-fA-F]{3}/.test(part)) {
            let colorCode = part.substring(0, 3); // e.g. "00F"
            let textContent = part.substring(3);  // e.g. "winter "
            html += `<span style="color:#${colorCode}">${textContent}</span>`;
        }
        // Check for Reset ($z) or Default ($g)
        else if (/^[zZgG]/.test(part)) {
             html += `<span style="color:inherit">${part.substring(1)}</span>`;
        }
        // Check for Style codes like $i (italic), $w (wide) - We just strip these to keep it clean
        else if (/^[iIwWnNsSoO]/.test(part)) {
            html += part.substring(1); // Just skip the code char
        }
        // Handle escaped dollar sign ($$) -> In split, this usually results in empty parts or tricky flow.
        // For simplicity in this specific format, we treat unknown codes as literals
        else {
            // If it's not a known code, put the $ back (it might be part of the name)
            html += "$" + part;
        }
    }
    
    return html;
}